"""Helpers for loading real plan fixtures in tests.

Tests run against the real plan fixtures generated by
``fixtures/terraform/generate.sh``. Edge cases are produced by mutating copies
of those real documents rather than by hand-writing plan JSON.
"""

import copy
import json
from pathlib import Path

from pydantic import JsonValue

FIXTURES_DIR = Path(__file__).resolve().parents[2] / "fixtures" / "plans"
# The placeholder behind the fixture's `sensitive = true` variable.
FIXTURE_SECRET = "example-not-a-real-secret"

_cache: dict[str, JsonValue] = {}


def load_plan(name: str) -> dict[str, JsonValue]:
    """A fresh, mutable copy of a real plan fixture."""
    if name not in _cache:
        _cache[name] = json.loads((FIXTURES_DIR / f"{name}.json").read_text(encoding="utf-8"))
    document = copy.deepcopy(_cache[name])
    assert isinstance(document, dict)
    return document


def resource_change(plan: dict[str, JsonValue], address: str) -> dict[str, JsonValue]:
    changes = plan["resource_changes"]
    assert isinstance(changes, list)
    for rc in changes:
        if isinstance(rc, dict) and rc.get("address") == address:
            return rc
    raise KeyError(address)
